apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distributed-notes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source: Your GitHub repository
  source:
    repoURL: https://github.com/thesarakasun/Distributed-System.git
    targetRevision: main
    path: k8s
  
  # Destination: Your AKS cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # Sync Policy: Automatic with Prune and Self Heal
  syncPolicy:
    automated:
      prune: true      # Delete resources that are no longer in Git
      selfHeal: true   # Force desired state even if manually changed
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
